### ISSUE TITLE
Current Height Approximation

### ISSUE THREAD

**Issue by 7jep7** [nyxxsudios/caelum#4]
uses Barometer to approximate current height

**Comment by 7jep7** [comment]
might be helpful (from http://stackoverflow.com/questions/23581378/how-to-get-barometric-altitude-in-android)
It seems that there is a method to do the pressure -> height converting:
You need to use the pressure sensor to measure the pressure then use the SensorManager.getAltitude(float, float) call to convert the measures pressure along with a reference sea level pressure to get the altitude.

The tricky bit is what to use as the reference pressure. This will change with the weather and will drift over time. Typically you would do some sort of calibration to set this values and possibly update it. It depends on your use case what the right solution is.

If properly calibrated pressure based altitude is considerably more accurate then gps based altitude especially if want you are interested in is altitude differences rather than absolute altitudes. With a bit of filtering on the raw pressure sensor values you can easily detect holding the phone at face level or arms length above your head which you want do with gps.

**Comment by gordonkoehn** [comment]
p = E^(-h/7500) pL0

**Comment by gordonkoehn** [comment]
Now I am using the inbuilt function.
